# Generated by Django 4.2.4 on 2023-09-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='gender',
            new_name='genders',
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre de genero'),
        ),
    ]
